#spring:
#  h2:
#    console:
#      enabled: true
spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/kotlin
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: ghdcoalss33
    jpa:
        hibernate:
            ddl-auto: create-drop
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: